TOP_DIR		= ..\..\..\..\..\..\..
!include		$(TOP_DIR)\mk\cond.mk

OBJ_DIR		= $(TOP_DIR)\obj\CPU1

LCFLAGS		=	\
		-fpack-struct \
		-fc9x-comment
		
LASFLAGS		=

SUBDIRS			= 

CSRC				= soapC.c soapServer.c stdsoap2.c
CPPSRC			=
CCSRC				= 
TCSRC				= 
ASRC				=
CFGSRC			= 

#-----------------------------------------------------------------------------
#-[ Don't modify below ]------------------------------------------------------
#-----------------------------------------------------------------------------

!include		$(TOP_DIR)\mk\env.mk

clean-subs:
